receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
   transform:
     trace_statements:
       - context: span
         statements:
         - set(attributes["peer.service"], attributes["net.peer.name"]) where attributes["net.peer.name"] != "" and name == "kong.balancer"

exporters:
  debug:
    verbosity: detailed
  otlphttp/ess:
    endpoint: ${ELASTIC_APM_SERVER_URL}
    headers:
      Authorization: "Bearer ${ELASTIC_APM_SECRET_TOKEN}"
        
service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [transform]
      exporters: [otlphttp/ess, debug]
    metrics:
      receivers: [otlp]
      exporters: [otlphttp/ess, debug]
    logs: 
      receivers: [otlp]
      exporters: [otlphttp/ess, debug]
  telemetry:
    logs:
      level: debug
